/*!40101 SET NAMES binary*/;
CREATE TABLE `share_data` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Share ID, uuid v4 generated by client',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Content for <title>',
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Content for <meta name=description>',
  `keyword` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Content for <meta name=keyword>',
  `image_url` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Default image url',
  `path` varchar(2083) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Real url path (includes hash and querystring)',
  `meta` json NOT NULL COMMENT 'Meta info',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `session_id` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Session ID generated by client IP',
  KEY `share_data_idx_path` (`path`),
  KEY `share_data_idx_session_id` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
